# Site settings
author: Bartholomew Fountain
title: "Why I decided to take up study Software Engineering?â€
header-img: img/home-bg.png
email: baertholomew@gmail.com
copyright_name: Bartholomew Fountain
description: > # this means to ignore newlines until "baseurl:"
  "Why I made up my mind!"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: AceOfTrade31
github_username:  James1934

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
